[tox]
envlist = py{39,310,311,312,313}, lint, check-format

[testenv]
description = Run tests
deps = pytest
commands = pytest {posargs:tests/}

[testenv:lint]
description = Run code linter
deps = ruff
commands = ruff check .

[testenv:lint-fix]
description = Fix linting errors
deps = ruff
commands = ruff check --fix .

[testenv:check-format]
description = Check code formatting
deps = ruff
commands = ruff format --check --diff .

[testenv:format]
description = Format code
deps = ruff
commands = ruff format .
