name: CI
on: [push, pull_request]

jobs:
  tox:
    name: Run Tox
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Run all envs
        uses: fedora-python/tox-github-action@c25c758f96dfb07b749a1034846f449166fd4979 # main
        with:
          tox_env: ${{ matrix.tox_env }}
    strategy:
      matrix:
        tox_env: [py310, py311, py312, py313, lint, check-format, typecheck]
    runs-on: ubuntu-latest

  mlflow-e2e:
    name: MLflow E2E
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: "3.12"
      - name: Run MLflow E2E tests
        run: pip install tox && tox -e mlflow-e2e
    runs-on: ubuntu-latest
